name: mydiet
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  file_picker: ^10.3.7
  shared_preferences: ^2.5.3

  # Notifications & Background Tasks
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  workmanager: ^0.9.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/dieta.json
    - assets/spesa_importata.json
    - ./.env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "icon.png"
